networks:
    guki:

services:
    nginx:
        image: nginx:stable
        container_name: guki_nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./code:/var/www/html
            - ./configs/vhosts/:/etc/nginx/conf.d/
            - ./configs/certs/:/etc/nginx/certs/:ro  # Certificates (read-only)
        depends_on:
            - php
        networks:
            - guki

    mysql:
        image: mysql:8.0
        container_name: guki_mysql
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - ${MYSQL_DATA_DIR:-./mysql_data}:/var/lib/mysql:rw
            - ${MYSQL_LOG_DIR:-./mysql_logs}:/var/log/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: Rkme#001
            MYSQL_DATABASE: rkme
            MYSQL_USER: rkme
            MYSQL_PASSWORD: Rkme#001
            MYSQL_ROOT_HOST: "%"  # Allows remote connections
            MYSQL_PORT: 3306
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_INITDB_SKIP_TZINFO: "yes"
            MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password  # Ensures compatibility with older clients
        networks:
            - guki

    php:
        build: 
            context: './builds/php/'
        container_name: guki_php
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ./code:/var/www/html
            - ./configs/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - guki

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: guki_phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - guki